alias ezs='vim ~/.zshrc'
alias glgl='glg --author=Liang'
alias lsu='less ~/.oh-my-zsh/plugins/ubuntu/ubuntu.plugin.zsh'
alias pkgl='dpkg --list  | less'
alias sdr2='screen -dR lliu2'
alias sdr='screen -dR lliu1'
alias wh='which'
